# ----- Production Dockerfile -----
FROM golang:1.14.0-alpine3.11

SHELL ["/bin/ash", "-c"]
ENV GO111MODULE=on
EXPOSE 8080

RUN mkdir public && mkdir app
ADD ./app /app
WORKDIR /app
RUN go build -o /public/app

CMD ["/public/app"]